name: CI/CD Pipeline to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Frontend Tests
      working-directory: ./frontend
      run: |
        npm ci
        npm run test

    - name: Backend Tests
      working-directory: ./backend
      run: |
        chmod +x mvnw
        ./mvnw clean test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build & Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: akmalalavi/task-backend:latest

    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: akmalalavi/task-frontend:latest
        build-args: |
          NEXT_PUBLIC_API_URL=/api

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          docker-compose pull
          docker-compose up -d